# Generated by Django 3.2 on 2023-06-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User1',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='User1Token',
            new_name='UserToken',
        ),
    ]
