# Generated by Django 3.2 on 2023-06-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='id_end',
            field=models.SmallIntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
