# Generated by Django 3.2 on 2023-06-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_id_end_job_is_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('A', '教师'), ('B', '学生'), ('1', '身份1'), ('2', '身份2'), ('3', '身份3'), ('4', '身份4'), ('5', '身份5'), ('6', '身份6')], default='B', max_length=2),
        ),
    ]
