# Generated by Django 3.2 on 2023-04-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(help_text='年龄', verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (0, '女')], max_length=5, verbose_name='性别'),
        ),
    ]
