# Generated by Django 3.2 on 2023-05-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class05Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=32, verbose_name='项目名')),
                ('vol_num', models.IntegerField(max_length=16, verbose_name='志愿者数量')),
                ('player_num', models.IntegerField(max_length=16, verbose_name='运动员数量')),
            ],
        ),
    ]
