# Generated by Django 3.2 on 2023-05-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_class05items_tourist_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class05Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=32, verbose_name='省份')),
                ('gold_medal', models.IntegerField(max_length=16, verbose_name='金牌数')),
                ('silver_medal', models.IntegerField(max_length=16, verbose_name='银牌数')),
                ('bronze_medal', models.IntegerField(max_length=16, verbose_name='铜牌数')),
                ('cctv', models.IntegerField(max_length=16, verbose_name='cctv观众数')),
                ('douyin', models.IntegerField(max_length=16, verbose_name='抖音观众数')),
                ('weixin', models.IntegerField(max_length=16, verbose_name='微信观众数')),
                ('others', models.IntegerField(max_length=16, verbose_name='其他渠道观众数')),
            ],
        ),
    ]
