# Generated by Django 3.2 on 2023-05-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_class05province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class01Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=32, verbose_name='年份')),
                ('knx', models.IntegerField(max_length=16, verbose_name='康乃馨')),
                ('yjx', models.IntegerField(max_length=16, verbose_name='郁金香')),
                ('mg', models.IntegerField(max_length=16, verbose_name='玫瑰')),
                ('xrk', models.IntegerField(max_length=16, verbose_name='向日葵')),
                ('mtx', models.IntegerField(max_length=16, verbose_name='满天星')),
                ('others', models.IntegerField(max_length=16, verbose_name='其他')),
            ],
        ),
    ]
