# Generated by Django 3.2 on 2023-05-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_class08store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class01Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=32, verbose_name='年龄')),
                ('money', models.IntegerField(max_length=16, verbose_name='销售额')),
            ],
        ),
        migrations.CreateModel(
            name='Class01City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32, verbose_name='年份')),
                ('money', models.IntegerField(max_length=16, verbose_name='销售额/万元')),
            ],
        ),
        migrations.CreateModel(
            name='Class01Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=32, verbose_name='年份')),
                ('month', models.IntegerField(max_length=16, verbose_name='月份')),
                ('money', models.IntegerField(max_length=16, verbose_name='销售额')),
            ],
        ),
    ]
