# Generated by Django 3.2 on 2023-05-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_class01city_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class02Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=32, verbose_name='游戏名')),
                ('free_player', models.CharField(max_length=32, verbose_name='空闲打手数')),
                ('active_player', models.IntegerField(max_length=16, verbose_name='活跃打手数')),
                ('sales', models.IntegerField(max_length=16, verbose_name='今日销售额')),
                ('finish_order', models.IntegerField(max_length=16, verbose_name='完成订单数')),
                ('unfinish_order', models.IntegerField(max_length=16, verbose_name='未完成订单数')),
            ],
        ),
        migrations.CreateModel(
            name='Class02Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_order', models.IntegerField(max_length=32, verbose_name='本月成单量')),
                ('total_order', models.CharField(max_length=32, verbose_name='本月接单量')),
                ('gile_order_rate', models.IntegerField(max_length=16, verbose_name='女生接单率')),
                ('gile_sales_rate', models.IntegerField(max_length=16, verbose_name='女生销售额占比')),
                ('inquiry_today', models.IntegerField(max_length=16, verbose_name='今日询盘量')),
                ('inquiry_month', models.IntegerField(max_length=16, verbose_name='本月询盘量')),
            ],
        ),
    ]
