# Generated by Django 3.2 on 2023-05-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_class02player_class02sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class02sales',
            old_name='gile_order_rate',
            new_name='girl_order_rate',
        ),
        migrations.RenameField(
            model_name='class02sales',
            old_name='gile_sales_rate',
            new_name='girl_sales_rate',
        ),
    ]
