# Generated by Django 3.2 on 2023-05-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_class06spot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class05Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.IntegerField(max_length=32, verbose_name='选手数')),
                ('volunteer', models.IntegerField(max_length=32, verbose_name='志愿者数')),
                ('bus', models.IntegerField(max_length=32, verbose_name='接待车辆数')),
                ('medic', models.IntegerField(max_length=32, verbose_name='医疗队数')),
            ],
        ),
    ]
