# Generated by Django 3.2 on 2023-05-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_class05info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class08Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=32, verbose_name='店名')),
                ('money', models.TextField(verbose_name='每天金额')),
            ],
        ),
    ]
