# Generated by Django 3.2 on 2023-06-04 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('uid', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('user_type', models.CharField(choices=[('A', '管理员'), ('B', 'Vip用户'), ('C', '普通用户')], max_length=1)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='User1Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drf.user1')),
            ],
        ),
    ]
