# Generated by Django 3.2 on 2023-06-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0003_user1_user1token'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user1',
            table=None,
        ),
    ]
